In [1]:
import pandas as pd

In [2]:
df_review  = pd.read_csv('../../Dataset/tripadvisor/reviews.csv')
df_offering = pd.read_csv('../../Dataset/tripadvisor/offerings.csv')

In [5]:
df_review.drop(['num_helpful_votes', 'via_mobile'], axis=1, inplace=True)

In [16]:
print(df_review.head())

                                             ratings  \
0  {'service': 5.0, 'cleanliness': 5.0, 'overall'...
1  {'service': 5.0, 'cleanliness': 5.0, 'overall'...
2  {'service': 4.0, 'cleanliness': 5.0, 'overall'...
3  {'service': 5.0, 'cleanliness': 5.0, 'overall'...
4  {'service': 4.0, 'cleanliness': 5.0, 'overall'...

                                             title  \
0        “Truly is "Jewel of the Upper Wets Side"”
1                        “My home away from home!”
2                                     “Great Stay”
3                             “Modern Convenience”
4  “Its the best of the Andaz Brand in the US....”

                                                text  \
0  Stayed in a king suite for 11 nights and yes i...
1  On every visit to NYC, the Hotel Beacon is the...
2  This is a great property in Midtown. We two di...
3  The Andaz is a nice hotel in a central locatio...
4  I have stayed at each of the US Andaz properti...

                                              author    date_stayed  \
0  {'username': 'Papa_Panda', 'num_cities': 22, '...  December 2012
1  {'username': 'Maureen V', 'num_reviews': 2, 'n...  December 2012
2  {'username': 'vuguru', 'num_cities': 12, 'num_...  December 2012
3  {'username': 'Hotel-Designer', 'num_cities': 5...    August 2012
4  {'username': 'JamesE339', 'num_cities': 34, 'n...  December 2012

   offering_id        date         id
0        93338  2012-12-17  147643103
1        93338  2012-12-17  147639004
2      1762573  2012-12-18  147697954
3      1762573  2012-12-17  147625723
4      1762573  2012-12-17  147612823

In [17]:
# 1. Extraindo os dicionários para novos DataFrames
df_ratings = pd.json_normalize(df_review['ratings'])
df_author = pd.json_normalize(df_review['author'])

# 2. Adicionando prefixos (opcional, mas recomendado para evitar conflitos)
df_ratings = df_ratings.add_prefix('rating_')
df_author = df_author.add_prefix('author_')

# 3. Concatenando de volta ao DataFrame original e removendo as colunas antigas
df_final = pd.concat([df_review.drop(columns=['ratings', 'author']), df_ratings, df_author], axis=1)

# Visualizar resultado
print(df_final.columns)

Index(['title', 'text', 'date_stayed', 'offering_id', 'date', 'id',
       'rating_service', 'rating_cleanliness', 'rating_overall',
       'rating_value', 'rating_location', 'rating_sleep_quality',
       'rating_rooms', 'rating_check_in_front_desk',
       'rating_business_service_(e_g_internet_access)'],
      dtype='object')

In [30]:
df_final.shape

(878561, 15)

In [22]:
df_review['author'].loc[0]

"{'username': 'Papa_Panda', 'num_cities': 22, 'num_helpful_votes': 12, 'num_reviews': 29, 'num_type_reviews': 24, 'id': '8C0B42FF3C0FA366A21CFD785302A032', 'location': 'Gold Coast'}"

In [29]:
df_review

,ratings,title,text,author,date_stayed,offering_id,date,id
0,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...","“Truly is ""Jewel of the Upper Wets Side""”",Stayed in a king suite for 11 nights and yes i...,"{'username': 'Papa_Panda', 'num_cities': 22, '...",December 2012,93338,2012-12-17,147643103
1,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",“My home away from home!”,"On every visit to NYC, the Hotel Beacon is the...","{'username': 'Maureen V', 'num_reviews': 2, 'n...",December 2012,93338,2012-12-17,147639004
2,"{'service': 4.0, 'cleanliness': 5.0, 'overall'...",“Great Stay”,This is a great property in Midtown. We two di...,"{'username': 'vuguru', 'num_cities': 12, 'num_...",December 2012,1762573,2012-12-18,147697954
3,"{'service': 5.0, 'cleanliness': 5.0, 'overall'...",“Modern Convenience”,The Andaz is a nice hotel in a central locatio...,"{'username': 'Hotel-Designer', 'num_cities': 5...",August 2012,1762573,2012-12-17,147625723
4,"{'service': 4.0, 'cleanliness': 5.0, 'overall'...",“Its the best of the Andaz Brand in the US....”,I have stayed at each of the US Andaz properti...,"{'username': 'JamesE339', 'num_cities': 34, 'n...",December 2012,1762573,2012-12-17,147612823
...,...,...,...,...,...,...,...,...
878556,{'overall': 4.0},“vil komme igen”,"Pænt hotel i et livligt miljø. Store værelser,...","{'username': '', 'id': '', 'location': ''}",NaN,84093,2008-08-31,51441576
878557,"{'service': 4.0, 'cleanliness': 5.0, 'overall'...",“excellent”,"un excellent hotel 4 *, pour un prix raisonnab...","{'username': 'dan016', 'num_reviews': 2, 'num_...",July 2008,84093,2008-07-18,18003332
878558,"{'cleanliness': 5.0, 'overall': 5.0, 'rooms': ...",“Un hotel eccezionale”,"L'hotel, situato in una zona tranquilla e a du...","{'username': '', 'id': '', 'location': ''}",July 2008,84093,2008-04-18,15564515
878559,"{'cleanliness': 5.0, 'overall': 5.0, 'rooms': ...",“Gerne wieder”,Sehr schön ausgestattetes Hotel in bester Lage...,"{'username': '', 'id': '', 'location': ''}",July 2008,84093,2008-04-01,15564508
878560,"{'service': 4.0, 'cleanliness': 4.0, 'overall'...",“Nuevo... novísimo. Estupendo lugar.”,El hotel está entre el aeropuerto y Washington...,"{'username': 'Basajaun', 'num_cities': 8, 'num...",March 2008,84093,2008-03-13,14259290

In [32]:
df_final.drop(columns=['rating_business_service_(e_g_internet_access)', 'rating_check_in_front_desk'], axis=1, inplace=True)

In [33]:
df_final.dropna()

,title,text,date_stayed,offering_id,date,id,rating_service,rating_cleanliness,rating_overall,rating_value,rating_location,rating_sleep_quality,rating_rooms
0,"“Truly is ""Jewel of the Upper Wets Side""”",Stayed in a king suite for 11 nights and yes i...,December 2012,93338,2012-12-17,147643103,5.0,5.0,5.0,5.0,5.0,5.0,5.0
1,“My home away from home!”,"On every visit to NYC, the Hotel Beacon is the...",December 2012,93338,2012-12-17,147639004,5.0,5.0,5.0,5.0,5.0,5.0,5.0
2,“Great Stay”,This is a great property in Midtown. We two di...,December 2012,1762573,2012-12-18,147697954,4.0,5.0,4.0,4.0,5.0,4.0,4.0
3,“Modern Convenience”,The Andaz is a nice hotel in a central locatio...,August 2012,1762573,2012-12-17,147625723,5.0,5.0,4.0,5.0,5.0,5.0,5.0
4,“Its the best of the Andaz Brand in the US....”,I have stayed at each of the US Andaz properti...,December 2012,1762573,2012-12-17,147612823,4.0,5.0,4.0,3.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
878556,“vil komme igen”,"Pænt hotel i et livligt miljø. Store værelser,...",NaN,84093,2008-08-31,51441576,NaN,NaN,4.0,NaN,NaN,NaN,NaN
878557,“excellent”,"un excellent hotel 4 *, pour un prix raisonnab...",July 2008,84093,2008-07-18,18003332,4.0,5.0,4.0,4.0,4.0,NaN,5.0
878558,“Un hotel eccezionale”,"L'hotel, situato in una zona tranquilla e a du...",July 2008,84093,2008-04-18,15564515,5.0,5.0,5.0,NaN,NaN,NaN,5.0
878559,“Gerne wieder”,Sehr schön ausgestattetes Hotel in bester Lage...,July 2008,84093,2008-04-01,15564508,5.0,5.0,5.0,NaN,NaN,NaN,5.0
878560,“Nuevo... novísimo. Estupendo lugar.”,El hotel está entre el aeropuerto y Washington...,March 2008,84093,2008-03-13,14259290,4.0,4.0,4.0,4.0,3.0,NaN,4.0

In [12]:
df_imdb = pd.read_csv('../../Dataset/imdb/ratings.csv')

In [10]:
df_imdb.dropna(subset='rating', inplace=True)

In [11]:
df_imdb

,username,rating,helpful,total,date,title,review
0,antonpopescu,10,492,534,27 September 2019,Who trusts Oscars anymore after they ignored ...,The best movie I ever saw and I watched hundre...
1,Ksa-2010,10,301,328,26 June 2019,I waited 5 years to watch it again\n,After watching this insane movie in the theatr...
2,Patterson13,10,894,1014,8 April 2015,Best movie I have seen in my life\n,"This movie was the best written, acted, visual..."
3,frank-ancestor-hunter,10,357,428,6 April 2015,Excellent Movie\n,I judge a movie by how long it takes me to rea...
4,christopher-stiedl,10,196,246,14 December 2015,Glad i didn't watch the trailer\n,Interstellar - Review<br/><br/>Certain things ...
...,...,...,...,...,...,...,...
932459,halo_fourteen,8,0,1,10 October 2003,A cinematic masterpiece\n,"I wasn't sure what to expect from the ""fourth ..."
932460,TheX-1,10,0,1,10 October 2003,"Its crazy, but impressive.... It's Tarantino.\n","Its crazy, but impressive.... It's Tarantino. ..."
932461,monkeysplayingfrisbee,10,0,1,10 October 2003,Oh yes! That's a 'bloody' good scrap!\n,Saw this last night and my god it's good!<br/>...
932462,tsjhangra,10,0,1,10 October 2003,Breathtaking experience\n,I've learned more about the story from the tra...
932463,fanni,7,0,1,18 December 2003,The Story of a Woman Who Wants To Revenge Her...,The Bride was once part of a group of female a...